#!/bin/bash

cat <<EOF > /home/ubuntu/app/.env
export JWT_SECRET=$JWT_SECRET
export DB_URL=$DB_URL
export DB_USERNAME=$DB_USERNAME
export DB_PASSWORD=$DB_PASSWORD
export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
EOF
